insert into `nation` values
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctica'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BQ', 'Bonaire'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvet Island'),
('BR', 'Brazil'),
('IO', 'British Indian Ocean Territory'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CV', 'Cape Verde'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CD', 'Democratic Republic of the Congo'),
('CK', 'Cook Islands'),
('CR', 'Costa Rica'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CW', 'Curacao'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('CI', "Cote d'Ivoire"),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Ethiopia'),
('FK', 'Falkland Islands (Malvinas)'),
('FO', 'Faroe Islands'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('TF', 'French Southern Territories'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HM', 'Heard Island and McDonald Mcdonald Islands'),
('VA', 'Holy See (Vatican City State)'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran, Islamic Republic of'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', "Korea, Democratic People's Republic of"),
('KR', 'Korea, Republic of'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', "Lao People's Democratic Republic"),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macedonia, the Former Yugoslav Republic of'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia, Federated States of'),
('MD', 'Moldova, Republic of'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestine, State of'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PN', 'Pitcairn'),
('PL', 'Poland'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('RO', 'Romania'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('RE', 'Reunion'),
('BL', 'Saint Barthelemy'),
('SH', 'Saint Helena'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin (French part)'),
('PM', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and the Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SX', 'Sint Maarten (Dutch part)'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('GS', 'South Georgia and the South Sandwich Islands'),
('SS', 'South Sudan'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SJ', 'Svalbard and Jan Mayen'),
('SZ', 'Swaziland'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan, Province of China'),
('TJ', 'Tajikistan'),
('TZ', 'United Republic of Tanzania'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TC', 'Turks and Caicos Islands'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UM', 'United States Minor Outlying Islands'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Viet Nam'),
('VG', 'British Virgin Islands'),
('VI', 'US Virgin Islands'),
('WF', 'Wallis and Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

INSERT INTO comment (article_id, author, content) VALUES
('1', '2', 'This is comment 1'),
('2', '3', 'This is comment 2'),
('3', '1', 'This is comment 3'),
('4', '2', 'This is comment 4'),
('3', '3', 'This is comment 5'),
('2', '3', 'This is comment 6');



INSERT INTO account (username, password, firstname, lastname, middlename, email, birthday, nation, avatar_path, role) VALUES
( 'user1', 'password1', 'firstname1', 'lastname1', 'middlename1', 'firstname1lastname1@gmail.com', '1970-01-01', 'NZ', 'images/avatar.jpg', '1'),
('user2', 'password2', 'firstname2', 'lastname2', 'middlename2', 'firstname2lastname2@gmail.com', '1970-01-02', 'NZ', 'images/avatar.jpg', '2'),
('user3', 'password3', 'firstname3', 'lastname3', 'middlename3', 'firstname3lastname3@gmail.com', '1970-01-03', 'NZ', 'images/avatar.jpg', '2'),
('user4', 'password4', 'firstname4', 'lastname4', 'middlename4', 'firstname4lastname4@gmail.com', '1970-01-04', 'NZ', 'images/avatar.jpg', '2'),
('user5', 'password5', 'firstname5', 'lastname5', 'middlename5', 'firstname5lastname5@gmail.com', '1970-01-05', 'NZ', 'images/avatar.jpg', '2'),
('user6', 'password6', 'firstname6', 'lastname6', 'middlename6', 'firstname6lastname6@gmail.com', '1970-01-06', 'NZ', 'images/avatar.jpg', '2'),
('user7', 'password7', 'firstname7', 'lastname7', 'middlename7', 'firstname7lastname7@gmail.com', '1970-01-07', 'NZ', 'images/avatar.jpg', '2'),
('user8', 'password8', 'firstname8', 'lastname8', 'middlename8', 'firstname8lastname8@gmail.com', '1970-01-08', 'NZ', 'images/avatar.jpg', '2'),
('user9', 'password9', 'firstname9', 'lastname9', 'middlename9', 'firstname9lastname9@gmail.com', '1970-01-09', 'NZ', 'images/avatar.jpg', '2');


INSERT INTO article (author, title, content) VALUES
  ('1', 'Title 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin.'),
  ('2', 'Title 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin.'),
  ('2', 'Title 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin.'),
  ('3', 'Title 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin.'),
  ('4', 'Title 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ornare libero nisl, in elementum sem lacinia ut. Proin in lectus metus. Mauris congue, ex vitae viverra sollicitudin, nisi urna accumsan ligula, ac vehicula ex ex et risus. Aliquam bibendum rutrum metus eu ultricies. Vivamus elit mi, ullamcorper ut sodales volutpat, tincidunt quis risus. Nulla hendrerit ex et sodales viverra. Proin molestie leo lacus, ac cursus tellus varius id. Praesent eu nulla nec quam iaculis molestie. Sed placerat urna in risus egestas, vel egestas metus fermentum. Aliquam pretium vitae tortor et facilisis. Proin non justo nibh. Nam commodo finibus pellentesque. Maecenas consequat bibendum mattis. Ut egestas non diam quis sollicitudin.')